server:
  port: 8222
spring:
  application:
    name: caijiazhengshop-gateway
eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url: # 客户端注册地址
      defaultZone: http://localhost:8888/eureka
  instance:
    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    prefer-ip-address: true
#zuul的动态路由配置
zuul:
  routes:
    caijiazhengshop-user:
      path: /caijiazhengshop-user  # 需要转发的路径
      serviceId: caijiazhengshop-user # 最终转发的微服务（名称）
    caijiazhengshop-web:
      path: /caijiazhengshop-web  # 需要转发的路径
      serviceId: caijiazhengshop-web # 最终转发的微服务（名称）
  SendErrorFilter:
    error:
      disable: true
